# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: RestHospitalProject-2
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: raviteja
    password: welcome
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9000
